spring:
  application:
    name: home-hub-agent

server:
  port: ${SERVER_PORT:8081}

node:
  container-name: ${NODE_CONTAINER_NAME:palworld}
  game-port: ${GAME_PORT:8211}
  protocol: ${GAME_PROTOCOL:udp}