spring:
  application:
    name: home-hub-agent

server:
  port: ${SERVER_PORT:8081}

node:
  container-name: ${NODE_CONTAINER_NAME:palworld}
  game-port: ${GAME_PORT:8211}
  protocol: ${GAME_PROTOCOL:udp}

palworld:
  rest-api:
    url: ${PALWORLD_URL:http://192.168.0.28:8212}
    username: ${PALWORLD_USERNAME:admin}
    password: ${PALWORLD_PASSWORD}